# GitHub Metrics Configuration for jabaldoo
# https://github.com/lowlighter/metrics

name: GitHub Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Base metrics
      - name: General metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: jabaldoo
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Warsaw
          template: classic
          config_display: large
          config_padding: 10%
          config_animations: yes
          config_order: base.header, isocalendar, languages, notable, achievements
          
          # Purple theme to match your color scheme
          config_colors: "#9D8CFF, #6E5DC6, #483C85, #211C40, #130E23"
          
          # Profile view counter
          plugin_people: yes
          plugin_people_types: followers, following

      # Language metrics
      - name: Languages and coding metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.language.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: jabaldoo
          base: ""
          template: classic
          config_display: large
          config_padding: 10%
          config_animations: yes
          
          # Languages used
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming, data, prose
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 2%
          
          # Recent activity
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      # Achievements and stats
      - name: Achievements and stats
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: jabaldoo
          base: ""
          template: classic
          config_display: large
          config_padding: 10%
          config_animations: yes
          
          # Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed
          
          # GitHub statistics
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          
          # GitHub stars
          plugin_stars: yes
          plugin_stars_limit: 4

      # Activity graph
      - name: Activity graph
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: jabaldoo
          base: ""
          template: classic
          config_display: large
          config_padding: 10%
          config_animations: yes
          
          # Activity
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_visibility: public
          plugin_activity_timestamps: yes
          
          # Habits
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          plugin_habits_from: 200
          plugin_habits_days: 14

      # Contribution snake animation
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Deploy to the output branch
      - name: Push snake animation
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
