name: Profile Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: jabaldoo
          template: classic
          plugin_languages: yes
          plugin_activity: yes

  streak:
    runs-on: ubuntu-latest
    needs: metrics
    steps:
      - name: Generate streak stats
        uses: github-readme-streak-stats.vercel.app?user=jabaldoo  # Direct API call
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}