name: GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:     # Allows manual triggering
  push:
    branches:
      - main

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    name: Update metrics
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: jabaldoo
          template: classic
          base: ""
          plugin_lines: yes
          plugin_languages: yes
          plugin_activity: yes
          plugin_isocalendar: yes
          config_languages_colors: "58A6FF,1F6FEB,3D6117"
          config_timezone: Europe/London

  streak-stats:
    runs-on: ubuntu-latest
    needs: generate-metrics
    steps:
      - name: Generate streak stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          user: jabaldoo
          theme: dark
          hide_border: true