name: Profile Metrics
on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight UTC
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: jabaldoo
          template: classic
          base: ""
          plugin_lines: yes
          plugin_languages: yes
          plugin_activity: yes
          plugin_isocalendar: yes
          config_timezone: Europe/London
          config_languages_colors: "58A6FF,1F6FEB,3D6117"
          config_display: columns