
name: Profile Metrics
on:
  schedule:
    - cron: "0 0 * * *"  # Daily updates at midnight UTC
  workflow_dispatch:      # Manual trigger enabled
  push:
    branches: [ "main" ]

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Critical permission fix
      actions: read
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: jabaldoo
          template: classic
          base: ""
          plugin_languages: yes
          plugin_activity: yes
          config_timezone: Europe/London  # Change to your timezone
          config_display: columns
          plugin_lines: no               # Disabled temporarily
          plugin_isocalendar: no         # Disabled temporarily

  streak:
    runs-on: ubuntu-latest
    needs: metrics
    permissions:
      contents: read
    steps:
      - uses: DenverCoder1/github-readme-streak-stats@main
        with:
          user: jabaldoo
          theme: dark
          hide_border: true